-- Ruta T5 Iturregui a San Juan

-- Terminal Iturregui a San Juan Dia Laboral (lunes - viernes)
INSERT INTO SCHEDULE (ROUTE, STOP_AREA, DIRECTION, SCHEDULE_TYPE, STOP_TIME) VALUES
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '05:00:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '05:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '06:00:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '06:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '07:05:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '07:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '07:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '08:10:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '08:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '08:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '09:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '09:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '10:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '10:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '10:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '11:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '11:35:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '11:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '12:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '12:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '13:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '13:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '14:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '14:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '15:10:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '15:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '16:10:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '16:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '16:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '17:10:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '17:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '17:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '18:10:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '18:30:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '18:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '19:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '19:50:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '20:20:00'),
  ('T5', 'ITURREGUI', 'SAN_JUAN', 'WORKDAY', TIME '20:50:00');

-- Terminal San Juan a Iturregui Dia Laboral (lunes - viernes)
INSERT INTO SCHEDULE (ROUTE, STOP_AREA, DIRECTION, SCHEDULE_TYPE, STOP_TIME) VALUES
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '05:00:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '05:30:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '06:00:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '06:35:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '07:05:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '07:35:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '08:12:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '08:42:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '08:52:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '09:12:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '09:32:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '09:52:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '10:12:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '10:32:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '10:58:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '11:28:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '11:58:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '12:13:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '12:28:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '12:58:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '13:28:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '13:43:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '13:58:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '14:28:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '14:58:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '15:28:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '15:43:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '15:58:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '16:28:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '16:52:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '17:12:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '17:32:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '17:52:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '18:12:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '18:32:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '19:12:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '19:32:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '19:52:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '20:12:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '20:32:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'WORKDAY', TIME '20:55:00');

WITH RECURSIVE t(n) AS (
  VALUES (time'06:00:00')
  UNION ALL
  SELECT n + interval '30 min' FROM t WHERE n + interval '30 min' <= time'20:00:00'
)
insert into schedule(route, stop_area, direction, schedule_type, stop_time)
(SELECT
   'T5' :: varchar(3) route,
   'ITURREGUI' :: varchar(10) stop_area,
   'SAN_JUAN' :: varchar(20) direction,
   'RESTDAY' :: VARCHAR(10) schedule_type,
   n stop_time
 FROM t);

WITH RECURSIVE t(n) AS (
 VALUES (time'14:55:00')
 UNION ALL
 SELECT n + interval '30 min' FROM t WHERE n + interval '30 min' <= time'20:25:00'
)
insert into schedule(route, stop_area, direction, schedule_type, stop_time)
(SELECT
  'T5' :: varchar(3) route,
  'SAN_JUAN' :: varchar(10) stop_area,
  'ITURREGUI' :: varchar(20) direction,
  'RESTDAY' :: VARCHAR(10) schedule_type,
  n stop_time
FROM t);

-- Terminal San Juan a Iturregui Dia Libre
INSERT INTO SCHEDULE (ROUTE, STOP_AREA, DIRECTION, SCHEDULE_TYPE, STOP_TIME) VALUES
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '06:00:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '07:10:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '07:45:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '08:15:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '08:45:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '09:15:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '09:45:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '10:24:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '10:54:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '11:24:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '11:54:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '12:24:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '12:54:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '13:24:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '13:54:00'),
  ('T5', 'SAN_JUAN', 'ITURREGUI', 'RESTDAY', TIME '14:24:00');
