-- Ruta T3 San Juan a Sagrado vía Ponce de Leon

DELETE FROM SCHEDULE where route = 'T3';

-- San Juan a Sagrado, día laboral
INSERT INTO SCHEDULE (ROUTE, STOP_AREA, DIRECTION, SCHEDULE_TYPE, STOP_TIME) VALUES
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '05:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '05:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '05:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '06:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '06:10:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '06:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '06:30:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '06:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '06:50:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '07:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '07:10:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '07:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '07:30:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '07:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '07:50:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '08:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '08:10:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '08:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '08:30:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '08:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '08:50:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '09:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '09:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '09:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '10:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '10:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '10:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '11:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '11:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '11:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '12:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '12:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '12:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '13:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '13:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '13:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '14:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '14:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '14:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '15:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '15:10:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '15:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '15:30:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '15:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '15:50:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '16:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '16:10:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '16:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '16:30:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '16:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '16:50:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '17:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '17:10:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '17:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '17:30:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '17:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '17:50:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '18:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '18:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '18:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '19:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '19:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '19:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '20:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '20:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '20:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '21:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '21:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '21:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '22:00:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '22:20:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '22:40:00'),
  ('T3', 'SAN_JUAN', 'SAGRADO_CORAZON', 'WORKDAY', TIME '23:00:00');

-- Sagrado a San Juan, dia laboral
INSERT INTO SCHEDULE (ROUTE, STOP_AREA, DIRECTION, SCHEDULE_TYPE, STOP_TIME) VALUES
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '05:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '05:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '05:40:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '06:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '06:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '06:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '06:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '06:40:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '06:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '07:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '07:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '07:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '07:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '07:40:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '07:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '08:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '08:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '08:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '08:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '08:40:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '08:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '09:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '09:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '09:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '09:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '10:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '10:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '10:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '11:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '11:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '11:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '12:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '12:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '12:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '13:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '13:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '13:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '14:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '14:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '14:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '15:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '15:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '15:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '15:40:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '15:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '16:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '16:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '16:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '16:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '16:40:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '16:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '17:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '17:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '17:20:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '17:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '17:40:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '17:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '18:00:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '18:15:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '18:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '18:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '19:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '19:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '19:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '20:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '20:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '20:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '21:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '21:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '21:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '22:10:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '22:30:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '22:50:00'),
  ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'WORKDAY', TIME '23:00:00');


WITH RECURSIVE t(n) AS (
  VALUES (time'06:00:00')
  UNION ALL
  SELECT n + interval '20 min' FROM t WHERE n < time'23:00:00'
)
insert into schedule(route, stop_area, direction, schedule_type, stop_time)
(SELECT
   'T3' :: varchar(3) route,
   'SAN_JUAN' :: varchar(10) stop_area,
   'SAGRADO_CORAZON' :: varchar(20) direction,
   'RESTDAY' :: VARCHAR(10) schedule_type,
   n stop_time
 FROM t);


WITH RECURSIVE t(n) AS (
  VALUES (time'06:10:00')
  UNION ALL
  SELECT n + interval '20 min' FROM t WHERE n < time'22:30:00'
)
insert into schedule(route, stop_area, direction, schedule_type, stop_time)
(SELECT
   'T3' :: varchar(3) route,
   'SAGRADO_CORAZON' :: varchar(20) stop_area,
   'SAN_JUAN' :: varchar(10) direction,
   'RESTDAY' :: VARCHAR(10) schedule_type,
   n stop_time
 FROM t);

-- Último viaje a las 11:00pm de Sagrado a SJ

INSERT INTO SCHEDULE(route, stop_area, DIRECTION, schedule_type, stop_time)
    VALUES ('T3', 'SAGRADO_CORAZON', 'SAN_JUAN', 'RESTDAY', TIME '23:00:00');